### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by yangkzz** [lauht/HD2AT#1]
You have a great project here! I was wondering if you could provide some information on where to obtain the dataset (./dataset & ./company_pool.txt in your codes) used in this project? Thank you in advance!

**Comment by lauht** [comment]
Thanks for your interest in our work!
Actually, the majority of our data is sourced from Yahoo Finance. But some original data is derived from Nasdaq Data Link (https://data.nasdaq.com/) as a supplement, and it is copyrighted.
Qlib may offer similar datasets which may reach similar performance.
